package com.hema.e_commerce.model.dataclass.allProducts

data class Variant(
    val admin_graphql_api_id: String,
    val barcode: String,
    val compare_at_price: Any,
    val created_at: String,
    val fulfillment_service: String,
    val grams: Int,
    val id: Double,
    val image_id: Double,
    val inventory_item_id: Int,
    val inventory_management: String,
    val inventory_policy: String,
    val inventory_quantity: Int,
    val old_inventory_quantity: Int,
    val option1: String,
    val option2: Any,
    val option3: Any,
    val position: Int,
    val presentment_prices: List<PresentmentPrice>,
    val price: String,
    val product_id: Double,
    val requires_shipping: Boolean,
    val sku: String,
    val taxable: Boolean,
    val title: String,
    val updated_at: String,
    val weight: Double,
    val weight_unit: String
)